aws/mynah-ui

- docs/DATAMODEL.md
- package.json
- src/components/chat-item/chat-item-form-items.ts
- src/components/form-items/select.ts
- Currently if select field is mandatory, the it will show the first option as selected by default, but not setting it as the currently selected value
- Set default value if select field is mandatory
> Set default value if select field is mandatory

- package-lock.json
- package.json
- src/components/chat-item/prompt-input/prompt-text-input.ts
- src/main.ts
- src/static.ts
When window gets focus, even though the autoFocus property is set to true, input field doesn't get focus.
Added autofocus to initialization, window focus and tab add/change events.
> added autofocus to input field

- .eslintignore
- docs/DATAMODEL.md
- example/src/commands.ts
- example/src/config.ts
- example/src/main.ts
- example/src/samples/sample-data.ts
- example/src/samples/sample-list-4.md
- package-lock.json
- package.json
- src/components/card/card-body.ts
- src/components/chat-item/chat-item-card.ts
- src/components/chat-item/chat-item-followup.ts
- src/components/chat-item/chat-wrapper.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
- src/components/source-link/source-link-header.ts
- src/main.ts
- src/static.ts
- src/styles/components/chat/_chat-items-container.scss
- src/styles/components/chat/_chat-overflowing-intermediate-block.scss
- Inside chat body, if there is a code block inside a list item it shows `<br/>` tags
- Prompt input field in Q Chat tabs doesn't stop after it reaches to the given maxUserInput
- Links in JetBrains inside Q Panel opens in Q panel's own window with middle mouse click.
- Card auto scrolling should be optional
- Removed break generation for list items (which is the supposed way from markedjs and github's own markdown styling)
- Prompt input `maxLength` value was set incorrectly, it was using the function declaration instead of function call.
- As we do for the clicks, we also mapped the middle clicks (`auxclick`) to the same handler functions, which will allow the JB side to control the event behavior (preventDefault) as they were doing for the normal clicks to avoid links opening inside Q …
> Several Bug fixes and feature additions

- example/webpack.config.js
- src/styles/_variables.scss
- src/styles/components/_icon.scss
- src/styles/components/_main-container.scss
- src/styles/components/_notification.scss
- src/styles/components/_source-link-header.scss
- src/styles/components/_syntax-highlighter.scss
- src/styles/components/card/_card.scss
- src/styles/components/chat/_chat-item-card.scss
- webpack.config.js
* The SCSS loader module did not support the SCSS `:export` feature, requiring the use of `@include` and maps or arrays created at the root level.
* This limitation also necessitated creating arrays and maps across nested SCSS files, increasing complexity.
* There were multiple redundancies, such as excessive `.token` declarations, which undermined the benefits of using SCSS as a preprocessor.
* Added `icss` mode to both `webpack.config.js` files.
* Tested in both `/examples` and `root` folders using `npm run watch` and build.
* Introduced new `@mixins`:
* `export-map` for leveraging the `:export` feature of SCSS.
* Added `@function` `flatten` to avoid nested unnamed functions within `@mixins`.
* Reduced redundant style class declarations using `@each` and `@for` loops.
* Created several …
> Refactor: SCSS

- package-lock.json
- package.json
- src/components/chat-item/chat-prompt-input.ts
When user types empty spaces at the beginning of lines inside prompt, it appears like a code block instead of a paragraph.
Removed empty spaces for each line.
> fixed paragraphs being converted to code blocks for user inputs

- .vscode/settings.json
- src/components/chat-item/chat-prompt-input.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
When a user types a quick action command starting with `/` or a context command starting with `@` and then loses focus, the command context is lost. When the user refocuses on the input field and continues typing, the quick pick overlay does not reappear, causing the command to never be picked up.
> [!TIP]
> Tomorrow Day Problems
* `chat-prompt-input.ts` could probably use some redundancy grouping for similar functionality
* `handleInputKeydown` has a complexity score of 54  
> fix: restore command prompt when blurred then focused

- package-lock.json
- package.json
- src/styles/components/chat/_chat-item-card.scss
- src/styles/components/chat/_chat-prompt-wrapper.scss
Fixing issue with long words causing overflow: [Filepaths are not wrapped](https://github.com/aws/mynah-ui/issues/76)
Version bump 4.15.3
Using styling to introduce word break.
Should cover cases like long path, class name or namespace.
> Fixed text overflow for long words in input and card prompt

- example/src/config.ts
- src/styles/_scrollbars.scss
- src/styles/styles.scss
Everything that needs / requires a scrollbar predicated by overflow conditions now has a scrollbar
* The gutter is `unset` meaning, it won't be there and be ugly.
* The draggable part is colored using css color mix blended in with white hs; `hsl(0, 100%, 100%)` @ `90%` which stays within the theme, and considerable enough for visual distinction
```
* {
scrollbar-gutter: unset;
scrollbar-color: color-mix(
in hsl,
var(--mynah-color-text-default),
hsl(0, 100%, 100%) 90%)
transparent;
}
```
> fix: #81 scrollbar

- example/src/commands.ts
- example/src/config.ts
- example/src/main.ts
- example/src/samples/sample-all-in-one.md
- example/src/samples/sample-data.ts
- example/src/samples/sample-table.md
- src/styles/components/_syntax-highlighter.scss
- src/styles/components/card/_card-body.scss
- src/styles/components/chat/_chat-item-card.scss
This resolves #76 
> Enter text into the mynah chatbox like awdaw/dawdaw/dawda/wdawdaw/dawdawd/awdad/awdawd/awdaw/dawd/, observe that when you enter the message, the text is not wrapped.
>
> From testing on the team, changing word-wrap css to break-word fixes this.
```css
code {
color: var(--mynah-color-syntax-code);
filter: brightness(0.95);
background-color: inherit;
white-space: pre-wrap;
word-wrap: break-word;
overflow-wrap: anywhere;
word-break: break-all;
}
```
```css
table {
table-layout: fixed;
thead {
background: var(--mynah-color-bg);
}
tbody {
tr:nth-child(even) {
background: var(--mynah-color-bg);
}
}
}
table, tr, th, td {
border: var(--mynah-border-width) solid var(--mynah-color-border-default);
border-collapse: collapse;
padding: var(--mynah-sizing-2);
word-break: …
```
> fix: #76 feature: markdown table styles feature: all markdown tags

- src/styles/components/card/_card-body.scss
Header does not seem to wrap well with default `word-wrap: normal`
before: 
after:
> fix: header in card not wrapping

- src/components/source-link/source-link-header.ts
- src/styles/components/_overlay.scss
Sometimes related link overlay (details) remain on screen and makes the UI panel unusable.
- Added a check if window looses focus then removes the active overlay for related link previews.
- Updated max width and height of the overlays to let user focus on some other point to automatically hide overlay items
- If content exceeds overlay size, it will not bleed from the edges anymore (`overflow: hidden`)
> Fixed link preview overlays remaining on screen sometimes

- src/styles/components/_toggle.scss
Scrollbars taking too much space which causes weird looking for tab selections
Removed scrollbar visibility at all from the tabs selection block which was the previous experience approved from the UX team.
> removed scrollbars from tab bar completely

- src/components/chat-item/chat-prompt-input.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
It is not possible to write any text which starts with @ character if they are not in the available contexts list. And if it is in the context list, it works as a context instead of user intended text.
- Added checks to avoid removal of the word if it starts with @ character and not in the available context selection list
- Added checks to send only the words start with @ character in the available context items list as part of the prompt object
- Added checks to paint only the words start with @ character in the available context items list, otherwise keep as normal texts
Here's how it works:
<video width="500" height="500" src='https://github.com/user-attachments/assets/68ed9202-7110-4c9f-bc28-8b988ab9182e' />
NOTE: Even though the word is partially matching with one of the context …
> Fix conflict of @ context selections and user intended annotations start with @

- package-lock.json
- package.json
- src/components/chat-item/chat-prompt-input.ts
The problem is described in related GitHub issue: https://github.com/aws/mynah-ui/issues/97
Revert fix for [another issue](https://github.com/aws/mynah-ui/issues/70) that is removing leading whitespace characters from the prompt. The previous fix is causing more impacting formatting issues. Also, the [change](https://github.com/aws/mynah-ui/issues/70) requested is not a bug, but a feature request. Current MynahUI treats any prompt as markdown, where [4 leading whitespaces means code block](https://www.markdownguide.org/basic-syntax/#code-blocks). Current MynahUI does not provide an option to input prompt as a plain text.
> Fix code indentation and nested formatting issue

- src/components/chat-item/chat-prompt-input.ts
Matched command is not filtering disabled command, allowing disabled command to be bypassed
Filter disabled command when finding the prompt & quick command match
> fix: quick action handling edge case not filtering disabled command

- package-lock.json
- package.json
- src/styles/components/_syntax-highlighter.scss
If you copy from the Mynah card with inline code and paste it into another place, it will contain new line breaks around inline code text.
The problem is described in more details in related issue: https://github.com/aws/mynah-ui/issues/98
Avoid using block elements for inline code.
Before:
After:
> Fix copy/paste for inline code

- package-lock.json
- package.json
- src/styles/components/_syntax-highlighter.scss
Inline code blocks are not properly aligned with the texts in latest VSCode and JetBrains IDEs.
https://github.com/aws/mynah-ui/issues/101
- Container box of inline code blocks are set to `inline-block` and vertical alignment is set to `middle`.
- Background and border pseudo selectors of the inline code blocks are realigned depending on the default line height.
- While the `top:50%` property moves the box to the middle of the parent container, instead of using negative `margin` with a calculated value (px, rem, em etc.) we're using `transform: translateY(-50%)`. Because the percentage values inside transform uses the target container's sizes, for this, it means that it will move the background and the border if the inline code half to top.
By submitting this pull request, I confirm that …
> Latest VSCode and MynahUI, inline codes are not aligned with normal texts

- src/styles/components/chat/_chat-prompt-wrapper.scss
The footer text of the chat dialogue should be centered. 
A simple CSS change to accommodate the centering through flex.
> Centered footer text

- src/styles/components/chat/_chat-prompt-wrapper.scss
Footer text is overflowing instead of wrapping
Add max width 100% to children of the footer text wrapper.
> Footer text now wraps instead of overflowing on smaller windows

- src/styles/components/chat/_chat-prompt-wrapper.scss
When there is a long text without and line breaks or spaces, send button shifts out from the right edge.
Overflow of the text input set to hidden to prevent overflowing.
> 120: send button shifts out of view

- src/styles/components/_syntax-highlighter.scss
Inline code elements formatted in a sent prompt message can overflow out of the visible chat window by being too long to fit. (issue #127)
Set whitespace to wrap in inline elements when overflowing.
> #127: Inlined code elements wrap onto new lines, normal code elements will not

- src/styles/_scss-variables.scss
- src/styles/components/_syntax-highlighter.scss
For readability of the code blocks in narrow screen conditions, it is better to wrap the code block texts since horizontal scrolling will cause too much movement.
Code blocks now take on a `white-space` of `pre-wrap` on screens narrower than 300px, ensuring the code is wrapped instead of overflowing with a scroll bar.
> #130: Code blocks now wrap text on screens narrower than 300px

- src/styles/components/_syntax-highlighter.scss
Inline code snippets can sometime overflow out of the screen, without wrapping / scrolling.
The content of inline code snippets now properly wraps onto new lines.
> Fixed inline code wrapping, previous fix did not cover full issue

- .github/workflows/beta.yml
- package-lock.json
- package.json
- src/main.ts
It is not possible to switch to a tab without user intent from the **inside** of mynah-ui. However, consumer can already have a user intent (for example by showing a notification on IDE and letting the user click it), In this case, even though there is a user intent, it will mismatch with the one on the mynah-ui side. 
Until finding a proper solution to between the consumer and the mynah-ui, we're skipping the eventId check,
> removed eventId check from selectTab

- src/components/chat-item/prompt-input/prompt-text-input.ts
In VSCode if you:
- write a message in chat
- focus somewhere else in the editor outside of chat
- wait for the response stream to finish
it will automatically focus the chat prompt
Only refocus the chat prompt if the document is currently focused
> fix: only re-focus after a response stream if the window is active

- README.md
- example/dev.js
- package.json
`npm run dev` && husky break things for module import
> [!WARNING]  
> `npm run dev` && husky break things for module import
```
(node:66958) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/../../example/dev.js:1
import open from 'open';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at internalCompileFunction (node:internal/vm:76:18)
at wrapSafe (node:internal/modules/cjs/loader:1283:20)
at Module._compile (node:internal/modules/cjs/loader:1328:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
at Module.load (node:internal/modules/cjs/loader:1203:32)
at Module._load (node:internal/modules/cjs/loader:1019:12)
at …
```
> fix: module import #135

- package-lock.json
- package.json
The global `npm install -g liveserver` installation on the `postinstall` script causes build issues for the AWS toolkit.
Removed the global package install, requiring users to do a manual global installation of the `liveserver` package. Also, going to upgrade contribution / PR docs to confirm it being tested on VSCode and Jetbrains.
> Removed global liveserver install to fix postinstall script

- src/styles/_variables.scss
- src/styles/components/chat/_chat-item-card.scss
URLs sent to chat by the user are barely visible in the VSCode light theme, which is used widely by developers, so for UX reasons this should be addressed.
Use an alternate color for links sent in cards with type `prompt`.
> Fixed URL color visibility issues on some themes

- src/styles/components/chat/_chat-item-tree-view.scss
When the text of a file is too long the actions are not visible and the icon shrinks down.
Flex shrink values properly adjusted.
> fixed file tree item title shrink

- src/components/__test__/syntax-highlighter.spec.ts
- src/components/button.ts
- src/components/card/card-body.ts
- src/components/syntax-highlighter.ts
- src/styles/components/card/_card-body.scss
- src/styles/components/chat/_chat-item-card.scss
The issue was reported in: https://github.com/aws/aws-toolkit-vscode/issues/5732
When there is a closing `span` tag inside a code block or inline code, it currently disappears and is not rendered. This is caused by old code in mynah-ui that would do some pre-processing on the html contents and replace certain span elements before they were rendered. This causes any span tag to be replaced and removed before they are rendered and this leads to the bug described above
See for example how the following input is rendered currently:
````
```
<span> span inside a codeblock </span>
```
`<span> span inside inline code </span>`
`````
To remove the old `keepHighlights` functionality. 
See an example card body that correctly renders the span tags after the fix: 
And the test case from above with …
> Fix disappearing span tags inside code blocks

- .github/workflows/new_pr.yml
- ui-tests/__test__/flows/welcome-mode.ts
The OS for the GitHub Action test runner currently runs Ubuntu, causing different results for E2E test runners compared to local dev environments.
Use MacOS-latest as test runner OS.
> Updated PR runner to use MacOS-latest

- src/styles/components/_button.scss
- src/styles/components/chat/_chat-item-tree-view.scss
Fixed border crop on buttons and file list wrappers
Sometimes one of the borders of the buttons or the file list wrapper is missing or looks thinner than it should be.
> fixed border crop on file list

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/guidance_request.md
- .github/ISSUE_TEMPLATE/improvement.md
The labels on the issue templates weren't all correctly matching up with our current labels. Also, we didn't really have a template for a (quality) improvement suggestion.
Updated our labels, fixed label mappings, added issue template for improvements.
> [improvement] Fixed GitHub issue template labels, added improvement issue template

- src/styles/_variables.scss
- src/styles/components/_syntax-highlighter.scss
Currently, the syntax highlighting can sometimes be suboptimal and unclear, compared to an IDE as VSCode.
Improved color mappings, mapped some more different token tags. 
> [improvement] better syntax highlighting

- src/components/chat-item/chat-prompt-input.ts
- src/styles/components/chat/_chat-prompt-wrapper.scss
Currently, when a command is waiting to be confirmed to be sent, the cursor still blinks in the prompt input textarea, even though the user can't type anything. Someone reported this as unexpected behavior, so an alternative should be considered.
Cursor is hidden when in command confirmation state. Also, now the command confirmation only shows up when a command is selected in the list through either `tab` or `space` (so `enter` / clicking will instantly send the command again, except for when there are arguments / parameters of course). 
> [improvement] consider hiding cursor in prompt input during command confirmation

- package-lock.json
cross-spawn and mismatch version in lockfiles are vulnerable
Bump to an uncompromised version with `npm audit fix`
> Bump vulnerable dependencies

- .github/workflows/new_pr.yml
Extended new PR GitHub workflow to send notification to Slack channel.
> Extended new PR GitHub workflow to send notification to Slack channel

- .github/workflows/new_pr.yml
Added "repository" key to the webhook payload, so that it can be reused for the `language-servers` and `language-server-runtimes` repositories as well.
> Added repository name to Slack PR webhook payload

- .husky/pre-push
- package-lock.json
- package.json
- src/styles/_variables.scss
- src/styles/components/chat/_chat-prompt-wrapper.scss
The footer text size and the line-height (in general) is too much and when there is a long disclaimer text it takes too much screen real estate.
The given font size to the footer was being overridden, made it !important to avoid overrides. Also, reduced the line-height in general as requested.
We have much more tests now and they are taking too much time and resources on local. Removing the `tests:e2e` step from the prepush to leave the test runs to github actions.
> Adjust footer text size

- src/components/chat-item/chat-prompt-input.ts
We should keep track of the last unsent user prompt when navigating with the up and down arrow through previous prompts. When the user navigates through previous prompts, they should be able to go back to the prompt they are currently writing which should not be reset. This behaviour is of particular relevance when writing a prompt and accidentally press the up or down arrow key, which would reset the prompt.
Keep track of the current prompt being written (last unsent user prompt)
> Avoid resetting last unsent user prompt when navigating with up and down arrows

- src/components/chat-item/chat-prompt-input.ts
- ui-tests/__test__/main.spec.ts
in our example mynah-ui we mark codeblock with \~~~~~~~~~~, different ides use \``` instead. This causes a small ui issue when navigating through prompts as the code blocks attached to previous prompts might not be trimmed correctly. More importantly, in this PR we make sure to remove the code marks ONLY if they appear at the very start of the codeAttachment, not the first occurrence. This issue could have potentially modified the user prompt if it contained an occurrence of  \~~~~~~~~~~ while the code block was marked via the \``` marks. In that case navigating through prompts would have caused an input like:
```
void main() {
print("~~~~~~~~~~");
print("Hello World");
print("Hello World");
}
```
to be transformed to 
```
void main() {
print("");
print("Hello World");
print("Hello …
```
> Fix code marks trimming for different ides

- package-lock.json
- package.json
Version update to **v4.21.2**
This update fixes two minor issues related to the recently introduced up/down arrows prompt navigation (like in the terminal):
1. When user is currently writing a prompt without sending it, and navigate through previous prompts via up/down arrows, and then goes back to the top of the list (current last unsent prompt), the unsent prompt was deleted, with this update the current unsent prompt is still visible and accessible. ([see PR](https://github.com/aws/mynah-ui/pull/198))
2. In VSCode and JetBrains, we fix the way code attachments are shown (when navigating to previous prompts which have a code attachment) by removing \``` at the beginning and end of the code snippets and potentially avoiding any replacement of the first instance of \~~~~~~~~~~ in the code …
```
> updated version to v4.21.2

- docs/USAGE.md
- src/helper/config.ts
- src/helper/dom.ts
- src/helper/events.ts
- src/helper/tabs-store.ts
- src/main.ts
When running e2e tests in vscode against mynah ui you have two options:
1. Create one mynah ui instance for all the subsequent tests, but this doesn't allow you to test specific functionality (e.g. the welcome page in VSCode shows up 3 times)
2. Create one mynah ui instance per test, but since mynah ui uses singletons and the module has been initialized already, its not actually providing a fresh state causing multiple extra events to be sent that shouldn't be
Add a `destroy` method for resetting all the singletons back to their initial state. This allows you to create a fresh mynah ui instance in every test
> feat: add public destroy command for resetting mynah ui state

- src/components/chat-item/chat-prompt-input.ts
If there is multiline text in prompt field, it is not possible to navigate to upper lines by using app arrow, it triggers historical navigation.
When there is text in the prompt field which is more than 1 line, until user approaches to the first line, keep the default behavior of the arrow keys.
> feat: up/down arrow navigation now only triggers when cursor is at the start or end of multiline inputs

- package.json
Packages were not installed in `ui-tests` when running dev script, which gave import errors after cleaning and rebuilding the main package.
Also `cd` into the `ui-tests` and run an `npm install`.
~- [ ] I have tested this change on VSCode~
~- [ ] I have tested this change on JetBrains~
> fix: dev script also installs packages in ui-tests

- src/components/chat-item/chat-prompt-input.ts
During the command confirmation step, users can still type @ to open the context suggestion menu. The @ itself does not get typed into the text area, but the overlay menu still opens.
The context menu does not open when max length of the prompt input is `0`.
> fix: don't show context menu when max input lenght is 0

- src/components/chat-item/chat-prompt-input.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
- src/styles/components/chat/_chat-prompt-wrapper.scss
- When using the up and down arrow keys to grab previous prompts like in a terminal, it is not possible to navigate through the text anymore. It should only trigger the historical previous/next prompt actions when on the first and last lines
- Cursor jumps to text end after up and down arrow actions even if there is no previous prompt available.
- Added current cursor line check before triggering historical prompt calls.
- Fixed unnecessary cleanup which causes a cursor jump to the end.
> Added cursor position check before running prompt history trigger

- ui-tests/__test__/flows/navigate-prompts/navigate-prompts-first-last-line-check.ts
- ui-tests/__test__/main.spec.ts
Recently, the up/down arrow prompt navigation has been updated to only trigger when the cursor is on the first or last line. This was not being tested yet.
Added an E2E test which covers this test case.
~- [ ] I have tested this change on VSCode~
~- [ ] I have tested this change on JetBrains~
> test: added e2e test for checking first/last line in prompt navigation

- ui-tests/__test__/flows/navigate-prompts/navigate-prompts-first-last-line-check.ts
Noticed a case of duplicated code strings in the e2e test I added yesterday.
Extracted the reusable strings into variables.
> refactor: extracted prompt texts in new test into variables

- package-lock.json
- package.json
- src/main.ts
The latest linkify [handler fix](https://github.com/aws/mynah-ui/pull/226) introduced a bug which the citations are not visible as clickable numbered links
Updated the pattern which checks the links are valid to also accept `[[1]](LINK)` format which Q returns as this. (Double square brackets)
> fix: Linkify skips double square brackets for text

- .github/workflows/new_pr.yml
Messages to Slack were being sent through the GitHub CI workflow, even for Draft PRs.
Filter to just run on non-draft PRs.
> Skip Slack message on draft PRs

- src/styles/components/chat/_chat-item-tree-view.scss
Allow file trees to scroll through overflow horizontally, instead of truncating text. As a preparation for larger file trees. Not sure if this is the way to go, and also not thoroughly tested, so highly experimental for now.
https://github.com/user-attachments/assets/e029a969-ffdc-47f7-aab1-591d5805e3d2
> EXPERIMENTAL: file tree with overflow-y scroll instead of truncation

- example/src/samples/sample-data.ts
- src/components/chat-item/chat-item-form-items.ts
- src/components/form-items/text-area.ts
- src/components/form-items/text-input.ts
- src/helper/validator.ts
The newly introduced form input validators should only apply if the field is non-empty or mandatory.
Updated the text input validator function to take into account these parameters.
> Fixed form validator bug; not taking non-mandatory empty fields into account

- docs/PROPERTIES.md
- example/src/config.ts
- example/src/connector.ts
- example/src/main.ts
- package-lock.json
- package.json
- src/components/chat-item/chat-item-card.ts
- src/components/chat-item/chat-item-tree-view-wrapper.ts
- src/components/chat-item/chat-item-tree-view.ts
- src/components/chat-item/chat-prompt-input.ts
- src/components/chat-item/prompt-input/prompt-input-quick-pick-item.ts
- src/components/chat-item/prompt-input/prompt-input-quick-pick-selector.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
- src/helper/quick-pick-data-handler.ts
- src/static.ts
- src/styles/components/chat/_chat-command-selector.scss
- src/styles/components/chat/_chat-prompt-wrapper.scss
- It is not possible to use the shift key during filtering the items when the context selector panel is open to add an underscore (`_`) into the search term. It closes the context selector panel when shift is pressed combined with any key
- When the action button on the right of the context group title clicked, the inserted `@` remains on the screen.
- Filtering in quick pick items does make the filter however it doesn't properly order, items contain the search term at the end of their text can appear at the top of the list. And it also shows some items doesn't match the term at all.
- Sometimes the context selection panel gets stuck and doesn't reflect to any input. It requires `esc` keypress to close it and reopen it back
- When choosing items from the context provider, the first item …
> Dogusata beta/fix card header refresh

- example/src/config.ts
- package-lock.json
- package.json
- src/helper/quick-pick-data-handler.ts
Filter on the context items doesn't sort expectedly. It should sort the items depending on their score and the higher score items should appear on top like the text starts with the match should be on top.
Even though the scoring structure was working as expected, sorting was completely missing before sending back the filtered list. Sorting is added to filter function.
Now, even if the `ex-dom.ts` record is above the `dom.ts` and also the `files` group is above the `symbols` group which holds the `DomBuilder` record, the `dom.ts` and `DomBuilder` records will appear on top and `ex-dom.ts` will appear on bottom when the search term is `dom`.
> Dogusata beta/fix context items filter sorting

- src/components/chat-item/prompt-input/prompt-text-input.ts
The incoming totalLines from the prompt input field is minimum 3 even if there is no text. And the currentLine and totalLines are not matching to trigger the down arrow button action which should grab the navigation history next item.
Reason behind that was the new update on the min-height for the prompt input field as 3 lines height. The calculation of the totalLines is changed to calculate it through a pointer. Instead of checking the block height. It adds a new pointer to the end of the block and checks its position to calculate. When done, it removes the pointer.
> fixed: wrong totalLines value in prompt input field

- src/components/chat-item/prompt-input/prompt-input-quick-pick-item.ts
When a context item is out of the visible area of the overlay, keyboard navigation to that item doesn't scroll the parent to show the item on screen.
Added scrollIntoView for the items when they're focused/in target by keyboard.
> fix: context item autoscrolls into view when in target

- example/src/config.ts
- src/components/chat-item/prompt-input/prompt-text-input.ts
- src/styles/components/chat/_chat-command-selector.scss
- Items with children in context selector is not clear until user hovers to them and see the right chevron that they have children
- When user keeps their mouse over the context selector block and uses keyboard up and down to target an element, it shows to focused items with the same weight.
- When an item is selected without an icon, it doesn't show the `@` character.
- Enabled the chevron to be visible all the time
- Added a hover check to the context selector overlay panel, if the panel is hovered then the target item will only be indicated with a border. It is still required since user may still hit enter from their keyboard. Even though the mouse target will be visually weighted more, users can still understand that the expected selection with keyboard enter will be the one with the …
> Dogusata/context selector chevron visbility and target+hover+visual update

- example/src/config.ts
- package-lock.json
- package.json
- src/components/chat-item/prompt-input/prompt-input-quick-pick-item.ts
- src/styles/components/chat/_chat-command-selector.scss
- In context or quick action command selector, sometimes spaces are not visible for the description.
- Replaced spaces of the string parts for description with `&nbsp;`. Since to be able to apply a middle ellipsis, we're splitting the text into two parts and wrap them with `span` elements. However, if the text end or start has a space character, it doesn't get rendered by default in html. To avoid it, we're replacing spaces with their char codes. It is not necessary to do a similar approach for any other character except space.
> fixed: spaces are not showing in context description

- src/components/chat-item/chat-prompt-input.ts
Type @ to open the menu. Use Cmd+A to select the entire prompt input and delete it. The menu stays open.
Check if the selection in the prompt input is equal to the full input, if so, close the context selector.
> Fix cmd+a and deleting not closing context selector

- docs/DATAMODEL.md
- src/components/chat-item/chat-item-card.ts
- src/helper/chat-item.ts
- src/helper/serialize-chat.ts
- src/static.ts
A data model for `InformationItem` and `InformationItemGroup`.
```typescript
export interface InformationItemGroup {
title?: string;
icon?: MynahIcons | MynahIconsType;
children: InformationItem[];
}
export interface InformationItem {
messageId?: string;
icon?: MynahIcons | MynahIconsType;
title?: string;
description?: string;
actions?: ChatItemButton[];
active?: boolean;
clickable?: boolean;
}
```
- `chatItems?` array on a tab can now contain either `ChatItem` objects or `InformationItemGroup` objects
- `InformationItemGroup` can optionally have a title to show above the group
- `InformationItem` must have a title, but can optionally have a description, be set to active to add a subtle background color, have a number of actions rendered on the right, and can have an onClick action on the …
> Added basic data model for InformationItem

- src/__test__/main.spec.ts
- src/helper/store.ts
It is possible to extend data store, defaults and subscribers event though they are typed.
Checking if the incoming key is available in the actual data model.
> fixed: data store, defaults and subscriber extensibility

- package.json
- src/styles/components/_detailed-list.scss
- src/styles/components/_form-input.scss
Form (text) input background colors do not adapt to theming colors properly;
Make the input itself transparent.
> Fixed form input bg color

- package-lock.json
- package.json
- src/helper/serialize-chat.ts
The HTML serialization for tabs was broken after the new changes to scroll behavior. The order of exported chat items was incorrect, and their position was off as well:
Fixed the transform and undid reversing the list:
> Fixed HTML export being in reverse order with incorrect transforms

- src/styles/components/chat/_chat-prompt-wrapper.scss
Padding is broken for the sticky card
- Fixed padding of sticky card
> fix: padding of sticky card

- src/helper/serialize-chat.ts
- The data retrieval from tabs in the serialization functions was not using the correct method, thus causing some items to be missing
- The HTML export is completely blank
- Use the correct method for retrieving ChatItems on a tab: `(MynahUITabsStore.getInstance().getTabDataStore(tabId).getValue('chatItems') as ChatItem[])`
- Update the HTML export to set visibility to visible, following the changes in #283 
> Fix chat export (markdown + HTML)

- docs/USAGE.md
- example/src/main.ts
- package-lock.json
- package.json
- src/components/detailed-list/detailed-list-sheet.ts
- src/components/sheet.ts
- src/helper/tabs-store.ts
- src/main.ts
- There was an unused `tabId` prop in the Sheet component and `openDetailedList()` function.
- Tab buttons would disappear when closing a tab in the tab bar which was currently not open.
- Remove the unused `tabId` prop from the internal Sheet component, made it optional but left it in the `openDetailedList()` function for backwards compatibility.
- Always refresh the selected tab and the bar itself whenever a tab is removed, to ensure the buttons are always rendered accordingly.
> Removed tabId from sheet props, fixed tabButtons disappearing

- src/components/__test__/syntax-highlighter.spec.ts
- src/components/syntax-highlighter.ts
- src/helper/dom.ts
- src/main.ts
- src/styles/components/_more-content-indicator.scss
- src/styles/components/_syntax-highlighter.scss
- ui-tests/__test__/flows/markdown-parser/markdown-parser.ts
- Code block max-height is breaking the inline-codes. 
- If you switch between tabs while the stream is live, when you back to the tab, code blocks are not having the expand button.
- While streaming, expand code block button blinks
- Code block action icons and show more resource link icons were not visible
- Add check to add max-height if the code is not inline.
- The expand button visibility and functionality 99% done through css now, so no flashing on expand button
- Empty cleaner was also cleaning up the icons since they didn't have content inside them, empty cleaner updated to check items with actual class names (not `<... class=""/>` but `<... class="with something"/>`)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fixed: codeBlock and inline code autoheight issues

- src/styles/components/chat/_chat-items-container.scss
See issue #281.
Only apply the loading bar styling to the last conversation container.
> Fixed bug where loading indicator was showing up on multiple streams

- src/helper/quick-pick-data-handler.ts
The context selector's search algorithm was too lenient, e.g. these super partial results at the bottom should never even be returned:
Return a score of `0` for all partial matches instead of building a score from partial containing matches.
> Adjusted context search algo to never include any completely partial results

- docs/DATAMODEL.md
- example/src/main.ts
- src/components/chat-item/chat-item-tree-file.ts
- src/main.ts
- src/static.ts
- `data?: Record<string, string>` added to `TreeNodeDetails`
- `onFileClick` extended with `fileDetails` param
> Extended onFileClick with full fileDetails

- package-lock.json
- package.json
- src/helper/style-loader.ts
- src/main.ts
Even though it is not expected, if there are two or more instances of MynahUI available in the consumer, because their style is being loaded even before they initialized, a conflict occurs between styles. 
To avoid style conflicts, styles are being loaded when an instance is created in the constructor.
> chore: move style loading to constructor

- src/components/detailed-list/detailed-list-item.ts
Every detailed list item description ends in a `}`
Remove extra `}` from innerHtml
Before
After
> fix: extra curly brace in detailed list item

- src/styles/components/form-items/_radio-group.scss
- Pair programming icon disappears if user turn off pair programming mode.
- Set `transform: scale(0.75)` and removed color style in `_radio-group.scss` file. 
Here is how I tested in my local VSC sandbox:
https://github.com/user-attachments/assets/6d48cb31-7271-46d6-a0e8-f45bdd1e647c
> Fix to update the tranform property in radio-group.scss file for pair-programming icon.

- example/src/samples/sample-data.ts
- src/styles/components/chat/_chat-item-card.scss
Header status fields without a status color applied should get the `disabled` color instead of the `weak` color.
Changed the color in case of no status:
> Disabled color for no-status header status fields

- src/styles/components/_form-input.scss
When open, the selection list does not have a themed background defined. It shows up in dark themes as white, and you may not see the item text.
Apply a background to selection items.
Verified using the sample app workbench.
> fix: apply background to selection list items

- src/components/tabs.ts
In Chromium-based envs (including JetBrains IDEs), _any_ non-primary click on a tab closes the tab. This includes right-click, middle click, and the forward/backward buttons on five-button mice
Only close tabs when clicked with the middle click button (I'm assuming this was the original intent)
> Middle click (and only middle click) closes tabs

- package-lock.json
- package.json
Version was incorrectly changed to `4.35.0-beta.7` through an unintended merge change.
Changed the version to `4.35.0` as intended.
> Changed version to 4.35.0

- docs/DATAMODEL.md
- example/src/config.ts
- src/components/__test__/chat-item/chat-item-form-items.spec.ts
- src/components/chat-item/chat-item-form-items.ts
- src/static.ts
When using the dropdown select component, you can use `mandatory: true` to hide the placeholder/"Please select" option from the dropdown. However doing so will also render an asterisk icon above it. We want to be able to hide the asterisk for certain cases, ie in prompt options for model selection.
Only render the asterisk if mandatory is true **and** ~~the form item title is not undefined~~ new flag `hideMandatoryIcon` is not set to true 
> feat: allow mandatory form item without asterisk

- src/styles/components/_detailed-list.scss
- when `clickable='true'`, there is no highlighting over the rows
- for `clickable='true'`, user sees highlighting over rows when hovered over
https://github.com/user-attachments/assets/edf46682-1483-486b-881b-76bcc73e97dd
> feat: add hover effect for clickable detailed list items

- example/src/main.ts
- example/src/samples/sample-data.ts
- src/styles/components/chat/_chat-prompt-wrapper.scss
- No background color for sticky card view.
- Adding background color for sticky card view.
- Removing the `padding-bottom: 0`, so that it adds some padding to the sticky card.
- Adding example data to use the sticky card in the [Live Mynah](https://aws.github.io/mynah-ui/).
> fix: updating some css styles to sticky card view

- .github/workflows/e2e-linux.yml
The `e2e-linux` testing CI script fails for PRs from forked branches as the `ref: ${{ github.head_ref }}` is unavailable here.
Replace this ref by `ref: ${{ github.event.pull_request.head.sha }}`.
> Use different ref for checkout to allow forked pull requests

- .github/workflows/e2e-linux.yml
E2E testing workflow fails for PRs from forked repos because they can't access the GitHub Container Registry.
Skip Docker caching on PRs from forked repos.
> Don't use Docker cache on forked PRs

- src/styles/components/chat/_chat-prompt-wrapper.scss
The sticky card does not have boarder and padding 
Change the css format to add boarder and padding for the sticky card. 
> fix: add boarder and padding to sticky card

- example/src/main.ts
- src/styles/components/chat/_chat-item-card.scss
We had a wrong dismiss icon on the top left, which do not meet UX design
Move the dismiss icon to the right
> fix: crossIcon position

- example/src/samples/sample-data.ts
- src/styles/components/chat/_chat-item-card.scss
Header status should be dimmed if the chat item has `muted: true`
Lower the opacity
Before: 
After:
> fix: status should be dimmed if muted is true

- example/src/commands.ts
- example/src/config.ts
- example/src/main.ts
- example/src/samples/sample-data.ts
- src/components/chat-item/chat-item-card.ts
- src/components/chat-item/chat-prompt-input.ts
- src/static.ts
- src/styles/components/chat/_chat-item-card.scss
- Merging beta [feat/quickAction-experience](https://github.com/aws/mynah-ui/tree/feat/quickAction-experience) branch to main.
* feat: Enable adding image to context from typing @image: or selecting from … by @yzhangok in https://github.com/aws/mynah-ui/pull/354
* Improving the unit test code coverage by @laileni-aws in https://github.com/aws/mynah-ui/pull/372
* feat: Add quickActionHeader for agentic  by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/375
* fix: radiogroup toggle will always stack vertically by @chungjac in https://github.com/aws/mynah-ui/pull/377
* Feat: Add a template for a bordered and padding card by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/376
* fix: only show commandActionHeader when it is not null by @Randall-Jiang in …
> Merging feat/quickAction-experience to main

- docs/DATAMODEL.md
- example/src/main.ts
- src/components/chat-item/chat-item-form-items.ts
- src/components/form-items/text-input.ts
- src/static.ts
There are two issues with how validation works on TextInput
- Validation error only appears onBlur. On single-item forms this leads to a confusing UX since submit button is disabled but no error message is shown (see recording)
- Validation error message appears onBlur even when the field hasn't been changed. When a field's autofocus is true, and user clicks `X` to exit the form, an error message shows up. (see recording)
- Add optional `validateOnChange` prop to TextInput. This allows consumers to opt-in to validation happening onChange for a specific field
- Only show validation error onBlur if user has touched the field
Screen recording **before fix**:
https://github.com/user-attachments/assets/f8619e36-f675-4c0b-9382-600c5283c15e
Screen recording **after fix**: …
> fix(text-input): validation error appears even if field is not changed, add validateOnChange prop

- docs/CONFIG.md
- docs/PROPERTIES.md
- example/src/main.ts
- src/main.ts
- src/static.ts
Currently, there is no way to intercept and handle the standard search shortcut (Cmd+F/Ctrl+F) within Mynah UI. Users want to be able to open chat history search with a keyboard shortcut.
Changes include:
- Added `enableSearchKeyboardShortcut` to config so consumers can opt-in to enable the keyboard shortcut 
- Added a new `onSearchShortcut` event handler that fires on Cmd+F or Ctrl+F
- Prevents the default search behavior
- Provides the current tab ID and event ID to the consumer for custom implementation
- Added documentation in `PROPERTIES.md` and `CONFIG.md`
- Implemented the event handler in the main MynahUI class
> feat: call onSearchShortcut on ctrl/cmd + f

- example/src/config.ts
- example/src/main.ts
- example/src/samples/sample-data.ts
- src/components/title-description-with-icon.ts
- When no icon is provided in `tabHeaderDetails`, the `mynah-ui-title-description-icon-wrapper` class adds unwanted left padding. 
- Modified `title-description-with-icon.ts` to conditionally apply icon wrapper styles.
- Only applies the `mynah-ui-title-description-icon-wrapper` class when an icon is provided
- Improves layout consistency when no icon is present
- The changes have been tested in the example application and work as expected.
> fix: UI Improvements for Non-Chat Tabs and Icon Wrapper Optimization

- example/src/main.ts
During the development, there's a `console.log()` used for testing was accidentally added.
Remove the console log.
> fix: remove the console log statement in example data

- src/styles/components/chat/_chat-prompt-wrapper.scss
- dropdown arrow spacing has too much spacing
- font size for dropdown options is too large
- we don't have a border if prompt input box is not in focus
- decrease spacing for dropdown arrow 
- decrease dropdown font size from `mynah-font-size-small` to `mynah-font-size-xsmall`
- always have border around prompt input box even when not in focus
https://github.com/user-attachments/assets/6795de13-505f-48b0-86ab-f2b646481ba1
> fix: decrease dropdown arrow spacing and always have border around prompt input box

- package-lock.json
- package.json
* fix: add log by using Log() function by @yzhangok in https://github.com/aws/mynah-ui/pull/411
* fix: decrease dropdown arrow spacing by @chungjac in https://github.com/aws/mynah-ui/pull/414
Use the Console on the right side of the MynahUI example page for logging.
https://github.com/user-attachments/assets/6795de13-505f-48b0-86ab-f2b646481ba1
> Bumping version to v4.36.2

- src/components/detailed-list/detailed-list.ts
- Dropdown list items disappear during scrolling when typing / in chat
- Added buffer zone to visibility calculations in handleScroll method
- Cache DOM position measurements to prevent inconsistent calculations
- Use mutually exclusive conditions to prevent add/remove conflicts in same iteration
> fix: prevent element removal during scroll

- example/src/config.ts
- src/components/chat-item/chat-item-form-items.ts
- src/components/form-items/select.ts
- src/static.ts
We would like to have a tooltip when hovering over select dropdown
Add tooltip when hovering over select dropdown. This only affects select dropdowns with `showDescriptionAsTooltip: true`
In this recording, the model selection dropdown has `showDescriptionAsTooltip: true`. We can see that the MCP dropdown still maintains its existing functionality with having the descriptions in the actual dropdown, and not a tooltip
https://github.com/user-attachments/assets/cbe1e219-125c-425f-b4de-5b85ea52e423
> feat: add tooltip to select dropdown

- .github/workflows/beta.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/unit-tests.yml
- package-lock.json
- package.json
- Node 18 is at EOL.
- Update node version from 18 to 24.
> feat: Bump up node version from 18 to 24

- example/src/config.ts
- src/components/chat-item/chat-item-form-items.ts
- src/components/form-items/select.ts
- src/static.ts
- we don't need `showDescriptionAsTooltip` field
- remove `showDescriptionAsTooltip` field
- fix tooltip so it can work on both VSC and JB
VSC and JB
https://github.com/user-attachments/assets/4145c232-a873-47ef-8b45-686bc9c93e05
https://github.com/user-attachments/assets/32e8c633-14b9-4685-8e31-82b9dfe7fd2c
https://github.com/user-attachments/assets/0b781b91-e871-45da-8d26-5c0f15962a79
> fix: edit tooltip to select dropdown
