package-lock.json
package.json
src/styles/components/card/_card-body.scss

Regarding **[this issue](https://github.com/aws/aws-toolkit-jetbrains/pull/4754#issuecomment-2261460060)**
table styles are reverted back

Reverted table styles back

---

src/components/chat-item/chat-prompt-input.ts

See #87 
- Added a handling logic for prompt that starts with one of the quick action commands. It will now execute the first match when user lost focus or copy paste the prompt causing the quick action to not be selected.
- Before
https://github.com/user-attachments/assets/9851e86c-0048-4a28-8645-6c732682f084
- After
https://github.com/user-attachments/assets/b5ed474d-03d9-4eff-afed-4d0d9e9365a8

fix: prompt quick action handling edge cases

---

README.md

The quick start guide in the readme said to use `npm run dev`, which is not a command we actively use.
The preferred way of development with MynahUI is now documented here.

Updated local environment quick start guide

---

package-lock.json
package.json

Relaxing  `marked` dependency semver for better compatibility

Relax marked dependency semver to ^14.1.0

---

.github/workflows/publish.yml

Also updated the publish GitHub Actions script to use MacOS-latest as runner OS.

Also updated publish action script to use MacOS-latest

---

README.md
docs/CONFIG.md
docs/DEVELOPER.md
docs/PROPERTIES.md
docs/USAGE.md

Minor improvements and typo fixing to documentation

doc:  minor typos fixs and improvements

---

package-lock.json
package.json

updated version to v4.21.0

---

package.json

Version needs to be bumped for release.

chore: bump version to 4.21.3

---

package-lock.json

chore: bump version in package-lock to 4.21.3

---

package.json

chore: bump version to 4.21.4

---

package-lock.json
package.json

Bumped beta version to 4.23.0-beta.6

---

docs/DATAMODEL.md
docs/PROPERTIES.md
example/src/main.ts
example/src/samples/sample-data.ts
package-lock.json
package.json
src/components/chat-item/chat-item-form-items.ts
src/components/chat-item/chat-prompt-input.ts
src/components/form-items/radio-group.ts
src/components/form-items/select.ts
src/components/form-items/stars.ts
src/components/form-items/text-area.ts
src/components/form-items/text-input.ts
src/helper/test-ids.ts
src/main.ts
src/static.ts
src/styles/components/_form-input.scss

Description field for the form items
Modifier key and enter key combination to submit the form

Form extensions

---

package-lock.json
package.json

Bumped version to 4.23.0-beta.8

---

.github/workflows/publish.yml

Publish test snapshots artifacts on publish workflow

---

docs/DATAMODEL.md
example/src/main.ts
package.json
src/components/icon.ts
src/components/icon/icon-importer.ts
src/components/icon/icons/history.svg

Added history icon

---

package-lock.json
package.json

Release new version **after** these PRs are merged:
https://github.com/aws/mynah-ui/pull/313
https://github.com/aws/mynah-ui/pull/312

chore: bump version to 4.31.1

---

src/helper/file-tree.ts

Some files were not showing up in the file-tree list:
With data:
```json
{
"messageId": "tooluse_8-ry4ir8SVq2PqDm_8s0tA",
"type": "answer",
"body": "\n\n\n\n\n\n",
"header": {
"fileList": {
"fileTreeTitle": "",
"filePaths": [
"/Users/laileni/Downloads/hupper/src/hupper",
"/Users/laileni/Downloads/hupper/src/hupper/tests",
"/Users/laileni/Downloads/hupper/tests",
"/Users/laileni/Downloads/hupper/tests/hupper"
],
"rootFolderTitle": "4 directories listed",
"flatList": true,
"collapsed": true,
"hideFileCount": true,
"details": {}
}
},
"buttons": [],
"padding": false,
"codeBlockActions": {
"insert-to-cursor": null,
"copy": null
}
}
```
Fixed the file indexing:

fix: some files not showing up in file tree

---

package-lock.json
package.json

- https://github.com/aws/mynah-ui/pull/351
- https://github.com/aws/mynah-ui/pull/350

Bumped version to 4.35.3

---

package-lock.json
package.json

- https://github.com/aws/mynah-ui/pull/352 by @Randall-Jiang 
- https://github.com/aws/mynah-ui/pull/361 by @Randall-Jiang 
- https://github.com/aws/mynah-ui/pull/336 by @avi-alpert 
- https://github.com/aws/mynah-ui/pull/356 by @Jurredr 
- https://github.com/aws/mynah-ui/pull/357 by @Jurredr 
- https://github.com/aws/mynah-ui/pull/358 y @Jurredr 
- https://github.com/aws/mynah-ui/pull/359 by @Jurredr 
- https://github.com/aws/mynah-ui/pull/360 by @Jurredr 
- https://github.com/aws/mynah-ui/pull/233 by @Jurredr 

Bumping up mynah version to 4.35.4

---

package-lock.json
package.json

- https://github.com/aws/mynah-ui/pull/366 by @avi-alpert 

chore: bump mynah version to 4.35.5

---

package-lock.json
package.json

- https://github.com/aws/mynah-ui/pull/368
- https://github.com/aws/mynah-ui/pull/369
- https://github.com/aws/mynah-ui/pull/370
- https://github.com/aws/mynah-ui/pull/371

Bumping up mynah version to 4.35.6

---

package-lock.json
package.json

* feat: Enable adding image to context from typing @image: or selecting from … by @yzhangok in https://github.com/aws/mynah-ui/pull/354
* Improving the unit test code coverage by @laileni-aws in https://github.com/aws/mynah-ui/pull/372
* feat: Add quickActionHeader for agentic  by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/375
* fix: radiogroup toggle will always stack vertically by @chungjac in https://github.com/aws/mynah-ui/pull/377
* Feat: Add a template for a bordered and padding card by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/376
* fix: only show commandActionHeader when it is not null by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/379
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Beta release: 4.36.0-beta.1

---

package-lock.json
package.json

* feat: Enable adding image to context from typing @image: or selecting from … by @yzhangok in https://github.com/aws/mynah-ui/pull/354
* Improving the unit test code coverage by @laileni-aws in https://github.com/aws/mynah-ui/pull/372
* feat: Add quickActionHeader for agentic  by @Randall-Jiang in https://github.com/aws/mynah-ui/pull/375
* fix: radiogroup toggle will always stack vertically by @chungjac in https://github.com/aws/mynah-ui/pull/377
* fix: Adding border and background color to chat item card summary by @laileni-aws in https://github.com/aws/mynah-ui/pull/384
* fix: adjust markdown point spacing as per requirements by @abhraina-aws in https://github.com/aws/mynah-ui/pull/382
* allow both capitalized and all lowercases command name used for image… by @yzhangok in …

Bumping up mynah ui version to 4.35.7

---

package-lock.json
package.json

* [fix(text-input): validation error appears even if field is not changed, add validateOnChange prop](https://github.com/aws/mynah-ui/pull/388) by @avi-alpert
* [fix: move pinContextHint to config texts](https://github.com/aws/mynah-ui/pull/389) by @avi-alpert
* [Add space and move the cursor after drag and drop to empty prompt, change image icon and improve overlay removal's latency](https://github.com/aws/mynah-ui/pull/387) by @yzhangok
**Full Changelog**: https://github.com/aws/mynah-ui/compare/v4.35.7...v4.35.8

Bumping up mynah version to 4.35.8

---

package-lock.json
package.json

* https://github.com/aws/mynah-ui/pull/392 by @yzhangok
* https://github.com/aws/mynah-ui/pull/394 by @avi-alpert 
* https://github.com/aws/mynah-ui/pull/391 by @dungdong-aws
* https://github.com/aws/mynah-ui/pull/393 by @yzhangok 
* @dungdong-aws made their first contribution in https://github.com/aws/mynah-ui/pull/391
**Full Changelog**: https://github.com/aws/mynah-ui/compare/v4.35.8...v4.35.9

Bumping up mynah version to  4.35.9

---

README.md
package-lock.json
package.json

- [docs: updating readme](https://github.com/aws/mynah-ui/commit/00df46a9fb2a405e6b2ba98016daccc000a9dee7)
- [fix: adding minimatch dependency in package.json](https://github.com/aws/mynah-ui/commit/1c3a68b9941f2767756353cda2c8b1b4cfa20ed1)

fix: adding minimatch dependency in package.json and updating docs.

---

package-lock.json
package.json

* fix: close quickpick when user presses space by @avi-alpert in https://github.com/aws/mynah-ui/pull/404
* feat: add description to options in detailed list and tooltip for select option by @dungdong-aws in https://github.com/aws/mynah-ui/pull/405
* fix: remove the console log statement in example data by @yzhangok in https://github.com/aws/mynah-ui/pull/409
* fix: adding minimatch dependency in package.json and updating docs. by @laileni-aws in https://github.com/aws/mynah-ui/pull/412
**Full Changelog**: https://github.com/aws/mynah-ui/compare/v4.36.0...v4.36.1

Bumping version to v4.36.1

---

example/src/main.ts

Use the Console on the right side of the MynahUI example page for logging.

fix: add log by using Log() function

---

docs/DATAMODEL.md
example/src/samples/sample-data.ts
src/__test__/components/form-items/form-item-pill-box.spec.ts
src/components/chat-item/chat-item-form-items.ts
src/components/form-items/__test__/form-item-pill-box.spec.ts
src/components/form-items/form-item-pill-box.ts
src/static.ts
src/styles/components/form-items/_form-item-pill-box.scss

This PR introduces a new `FormItemPillBox` component to the Mynah UI library, enabling users to input multiple values in a tag/pill format. This component is particularly useful for scenarios where users need to enter multiple related items like skills, technologies, arguments, or categories.
- **Added FormItemPillBox component** (src/components/form-items/form-item-pill-box.ts)
- Supports multi-value input with pill/tag visualization
- Users can add values by pressing Enter
- Individual pills can be removed
- Includes validation support and accessibility features
- **Enhanced ChatItemFormItemsWrapper** (src/components/chat-item/chat-item-form-items.ts)
- Added support for pillbox form item type
- Integrated validation handling for pill box inputs
- Updated type definitions to include the …

feat: Add FormItemPillBox Component for Multi-Value Input

---

package-lock.json
package.json

* feat: Add FormItemPillBox Component for Multi-Value Input @laileni-aws in https://github.com/aws/mynah-ui/pull/418
* feat: support rendering file list as pills by @ctlai95 in https://github.com/aws/mynah-ui/pull/419
**Full Changelog**: will add
https://github.com/user-attachments/assets/3718719e-0a28-454c-96bd-e7d4205513be

Bumping version to v4.36.3

---

package-lock.json
package.json

Beta release
Bump version 4.36.4-beta.1

chore: bump version 4.36.4-beta.1

---

package-lock.json
package.json

- fix: update file pill styles #422 @ctlai95 https://github.com/aws/mynah-ui/pull/422
- fix: remove existing status before updating with a new one #423 @ctlai95  https://github.com/aws/mynah-ui/pull/423
- feat: support markdown when renderAsPills is true #424 @ctlai95  https://github.com/aws/mynah-ui/pull/424
- feat: custom dropdown component #386 @dungdong-aws https://github.com/aws/mynah-ui/pull/386
https://github.com/user-attachments/assets/4f42c0ce-42b6-4644-bfb3-284445e9e406
https://github.com/user-attachments/assets/0d68424a-ca81-4c34-a3d3-bb3786240ad2

bump version to 4.36.4

---

package-lock.json
package.json

* fix: reduce icon complexity and transparency layers for Eclipse Webkit by @shruti0085 in https://github.com/aws/mynah-ui/pull/429
* fix: typewriter animation queue delay by @ctlai95 in https://github.com/aws/mynah-ui/pull/430
**Full Changelog**: https://github.com/aws/mynah-ui/compare/v4.36.4...v4.36.5

Bumping up the mynah-ui version to 4.36.5

---

package-lock.json
package.json

- feat: Bump up node version from 18 to  by @laileni-aws https://github.com/aws/mynah-ui/pull/435
- fix: edit tooltip to select dropdown by @chungjac  https://github.com/aws/mynah-ui/pull/442
https://github.com/user-attachments/assets/4145c232-a873-47ef-8b45-686bc9c93e05
https://github.com/user-attachments/assets/32e8c633-14b9-4685-8e31-82b9dfe7fd2c
https://github.com/user-attachments/assets/0b781b91-e871-45da-8d26-5c0f15962a79

bump version to 4.36.8
